/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsListIdTasksRouteImport } from './routes/lists.$listId.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdTasksRoute = ListsListIdTasksRouteImport.update({
  id: '/lists/$listId/tasks',
  path: '/lists/$listId/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lists/$listId/tasks': typeof ListsListIdTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lists/$listId/tasks': typeof ListsListIdTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lists/$listId/tasks': typeof ListsListIdTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lists/$listId/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lists/$listId/tasks'
  id: '__root__' | '/' | '/lists/$listId/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListsListIdTasksRoute: typeof ListsListIdTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId/tasks': {
      id: '/lists/$listId/tasks'
      path: '/lists/$listId/tasks'
      fullPath: '/lists/$listId/tasks'
      preLoaderRoute: typeof ListsListIdTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListsListIdTasksRoute: ListsListIdTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
